#!/bin/sh

REPO_PATH=$(dirname $(realpath $0))/..
SCRIPT_DIR=$0
SERVER_PATH=$REPO_PATH/src/server.py
WEB_PATH=$REPO_PATH/web
WEB_BUILD_PATH=$WEB_PATH/dist

python $SERVER_PATH --web --web_dir $WEB_BUILD_PATH --workflow_dir . --nodes_dir ./nodes $@
