# Simple workflow for deploying static content to GitHub Pages
name: Test building docs

on:
  push:
    branches: ["5-steppable-nodes"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build Graphbook Docs
        run: |
          pip install -r docs/requirements.txt
          make -C docs html
