name: Publish Graphbook to PyPI

on:
  workflow_dispatch:

jobs:
  pypi:
    runs-on:
      group: larger-runners
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout latest tag
        run: git checkout $(git describe --tags --abbrev=0)
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build and Publish
        run: |
          make package
          uv publish --token ${{ secrets.PYPI_PASSWORD }}
