name: Publish Graphbook to Test PyPI

on:
  workflow_dispatch:

jobs:
  pypi:
    runs-on:
      group: larger-runners
    steps:
      - uses: actions/checkout@v4
      - run: |
          pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up Test PyPI Repository
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
      - name: Build and Publish
        run: |
          make package
          poetry publish -r test-pypi -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.TEST_PYPI_PASSWORD }}
